### ISSUE TITLE
Missing lib packages issue

### ISSUE THREAD

**Issue by sciutand** [JakeWharton/sdk-manager-plugin#116]
when trying to provision a VM instance I get:

```
root@7ef4cf1b7638:/var/jenkins_home/workspace/1tap.onetap-android-receipts.builder# ./gradlew assemble
Android SDK not found. Downloading...
SDK extracted at '/root/.android-sdk'. Writing to local.properties.
org.eclipse.jgit.transport.FetchResult@1a2724d3
Merge of revisions 76fa6c1c40d6f1f7427f5fd026f86302f1ee5361, 76fa6c1c40d6f1f7427f5fd026f86302f1ee5361 with base 76fa6c1c40d6f1f7427f5fd026f86302f1ee5361 using strategy recursive resulted in: Already-up-to-date. 
Build tools 23.0.3 missing. Downloading...
Platform tools missing. Downloading...
Compilation API android-23 missing. Downloading...
Support library repository missing. Downloading...
Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAnimatedVectorDrawable2330Library UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72330Library UP-TO-DATE
:app:prepareComAndroidSupportDesign2330Library UP-TO-DATE
:app:prepareComAndroidSupportRecyclerviewV72330Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42330Library UP-TO-DATE
:app:prepareComAndroidSupportSupportVectorDrawable2330Library UP-TO-DATE
:app:prepareComJakewhartonTimberTimber412Library UP-TO-DATE
:app:prepareIoOnetapKit0011SNAPSHOTLibrary UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResourcesjava.io.IOException: Cannot run program "/root/.android-sdk/build-tools/23.0.3/aapt": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:163)
	at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:106)
	at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 4 more
```

to make it work I had to install these two packages:

```apt-get install lib32stdc++6 lib32z1```

Would be nice it the manager would deal with that too.

**Comment by JakeWharton** [comment]
That's an OS-specific requirement and I don't want this tool having to manage "native" dependencies for the host OS.

**Comment by sciutand** [comment]
Sounds good
